POST http://localhost:5157/exercises
Content-Type: application/json

{
    "linkedWorkoutID": "af51656b-7c35-4710-9ddd-d8b0a821c554",
    "exerciseName": "Bench press",
    "numberOfSets": 5,
    "weightEachSet": [
        60.0,
        80.0,
        90.0,
        100.0,
        112.5
    ],
    "repsEachSet": [
        12,
        8,
        5,
        3,
        2
    ],
    "notes": ""
}