@id=00000000-0000-0000-0000-000000000002

PUT http://localhost:5157/exercises/{{id}}
Content-Type: application/json

{
    "linkedWorkoutID": "00000000-0000-0000-0000-000000000001",
    "exerciseName": "Bench press",
    "numberOfSets": 5,
    "weightEachSet": [
        60.0,
        80.0,
        90.0,
        100.0,
        112.5
    ],
    "repsEachSet": [
        12,
        8,
        5,
        3,
        2
    ],
    "notes": ""
}